version: '3'
services:
  api:
    image: node:16-alpine
    container_name: shooesstore_api
    restart: always
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - 3001:3001
    tty: true
    stdin_open: true
    depends_on:
      - database

  database:
    image: mysql:8.0.29
    restart: always
    ports:
      - 3306:3306
    container_name: shooesstore_db
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=shooesstore
    volumes:
      - ./shooesstore.sql:/docker-entrypoint-initdb.d/shooesstore.sql
      - ./shooesstore-db:/var/lib/mysql